# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('B_Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('brandName', models.TextField(default='')),
                ('modelName', models.TextField(default='', null=True)),
                ('version', models.TextField(default='', null=True)),
                ('link', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('B_Id', models.IntegerField(default=0)),
                ('L_Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('fuel', models.TextField(default=0)),
                ('color', models.TextField(default=0)),
                ('usedOrNew', models.TextField(default=0)),
                ('doors', models.TextField(default=0)),
                ('gearBox', models.TextField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
