# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandId', models.IntegerField(default=0)),
                ('brandName', models.TextField(default='')),
                ('modelName', models.TextField(default='')),
                ('versionName', models.TextField(default='')),
                ('linkToBrand', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('fuel', models.TextField(default=0)),
                ('color', models.TextField(default=0)),
                ('usedOrNew', models.TextField(default=0)),
                ('doors', models.TextField(default=0)),
                ('gearBox', models.TextField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('bId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='InvalidLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkId', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('linkText', models.TextField(default='')),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkId', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('link', models.TextField(default='')),
                ('parsed', models.BooleanField(default=False)),
                ('brId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='lId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.Link'),
        ),
    ]
